-- DROP TABLE 
drop table IMAGE_STORE;
drop table IMAGE_FILE;

--테이블초기화
TRUNCATE TABLE IMAGE_STORE;
TRUNCATE TABLE IMAGE_FILE;

-- DROP INDEX
DROP INDEX IX_IMAGE_STORE_01;
DROP INDEX IX_IMAGE_FILE_01;

-- DROP SEQUENCE
drop sequence "PPL_IMG_DBADM"."SQ_IMAGE_FILE_01";

------------------
-- 테이블 생성
------------------
-- 이미지 검색
CREATE TABLE IMAGE_STORE (
MAIN_KEY				VARCHAR2(14)  	  							NOT NULL,
BRANCH_CODE				VARCHAR2(20)								NULL,
BRANCH_TITLE			VARCHAR2(50)								NULL,
GUIDE_NAME				VARCHAR2(50)    							NULL,
EMPLOYEE_NAME			VARCHAR2(50)    							NULL,
EMPLOYEE_ID 			VARCHAR2(50)								NULL,
CUSTOMER_NAME			VARCHAR2(50)    							NULL,
DOC_MAPPING_COUNT		NUMBER(3) 		DEFAULT 0					NOT NULL, 
PREVIOUS_DEVICE_INFO	VARCHAR2(30)    							NULL,
INSOURCE_ID				VARCHAR2(15)    							NULL,	
INSOURCE_TITLE			VARCHAR2(100)    							NULL,
TASK_KEY				VARCHAR2(20)								NULL,
MEMO					VARCHAR2(255)    							NULL,	
TEL						VARCHAR2(20)								NULL,
CREATE_TIME				TIMESTAMP		DEFAULT CURRENT_TIMESTAMP   NOT NULL,
MODIFY_TIME				TIMESTAMP		DEFAULT CURRENT_TIMESTAMP	NULL,
CONSTRAINT PK_IMAGE_STORE PRIMARY KEY (MAIN_KEY) USING INDEX TABLESPACE TS_PPL_IMG_IDX_01
) TABLESPACE TS_PPL_IMG_DAT_01;

COMMENT ON TABLE IMAGE_STORE    					IS    '이미지 테이블';
COMMENT ON COLUMN IMAGE_STORE.MAIN_KEY				IS    '메인키(IMAGE_FILE.MAIN_KEY 테이블과 조인키)';
COMMENT ON COLUMN IMAGE_STORE.BRANCH_CODE			IS    '지점코드';
COMMENT ON COLUMN IMAGE_STORE.BRANCH_TITLE			IS    '지점명';
COMMENT ON COLUMN IMAGE_STORE.GUIDE_NAME			IS    '안내원';
COMMENT ON COLUMN IMAGE_STORE.EMPLOYEE_NAME			IS    '등록자 명(업무담당자 명)';
COMMENT ON COLUMN IMAGE_STORE.EMPLOYEE_ID			IS    '등록자 번호(업무담당자 번호)';
COMMENT ON COLUMN IMAGE_STORE.CUSTOMER_NAME			IS    '고객명';
COMMENT ON COLUMN IMAGE_STORE.DOC_MAPPING_COUNT		IS    '매핑 개수 (IMAGE_FILE.MAIN_KEY)';
COMMENT ON COLUMN IMAGE_STORE.PREVIOUS_DEVICE_INFO	IS    '정보전달 출발지 디바이스 정보';
COMMENT ON COLUMN IMAGE_STORE.INSOURCE_ID			IS    '업무코드';
COMMENT ON COLUMN IMAGE_STORE.INSOURCE_TITLE		IS    '업무명';
COMMENT ON COLUMN IMAGE_STORE.TASK_KEY				IS	  '업무키(접수번호)';
COMMENT ON COLUMN IMAGE_STORE.MEMO					IS    '메모';
COMMENT ON COLUMN IMAGE_STORE.TEL					IS    '전화번호';
COMMENT ON COLUMN IMAGE_STORE.CREATE_TIME			IS    '생성시각';
COMMENT ON COLUMN IMAGE_STORE.MODIFY_TIME			IS    '수정시각';
 
-- 이미지 정보
CREATE TABLE IMAGE_FILE (
MAIN_KEY 			VARCHAR2(14)     							NOT NULL,
DOC_ID		 		VARCHAR2(10)     							NOT NULL,
DOC_TITLE			VARCHAR2(255)								NULL,
PAGE_CNT	 		NUMBER(3)  		DEFAULT 1					NULL,
VERSION_INFO		NUMBER(3)   	DEFAULT 1					NOT NULL,
DOC_TYPE			VARCHAR2(10)     							NULL,
DELETE_YN			CHAR(1) 		DEFAULT 'N'					NULL,
FUNNELS				VARCHAR2(100)								NULL,
FILE_ID				VARCHAR2(20)								NOT NULL,
FILE_NAME	 		VARCHAR2(255)								NULL,
FILE_ORDER			NUMBER(3)		DEFAULT 0					NOT NULL,
CREATE_TIME 		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP   NOT NULL,
MODIFY_TIME 		TIMESTAMP     	DEFAULT CURRENT_TIMESTAMP	NULL,
CONSTRAINT PK_IMAGE_FILE PRIMARY KEY (MAIN_KEY, DOC_ID, VERSION_INFO) USING INDEX TABLESPACE TS_PPL_IMG_IDX_01
) TABLESPACE TS_PPL_IMG_DAT_01;

COMMENT ON TABLE IMAGE_FILE    						IS    '이미지 파일 테이블';
COMMENT ON COLUMN IMAGE_FILE.MAIN_KEY 				IS    '메인키(IMAGE_STORE.MAIN_KEY 테이블과 조인키)';
COMMENT ON COLUMN IMAGE_FILE.DOC_ID			   		IS    '문서 아이디';
COMMENT ON COLUMN IMAGE_FILE.DOC_TITLE			   	IS    '문서 명(서식 명)';
COMMENT ON COLUMN IMAGE_FILE.PAGE_CNT				IS    '페이지 수';
COMMENT ON COLUMN IMAGE_FILE.VERSION_INFO			IS    '버전정보';
COMMENT ON COLUMN IMAGE_FILE.DOC_TYPE				IS    '문서타입(IMAGE, PDF, ETC)';
COMMENT ON COLUMN IMAGE_FILE.DELETE_YN	 	  		IS    '삭제여부(Y/N)';
COMMENT ON COLUMN IMAGE_FILE.FUNNELS				IS    '문서 유입경로(cyber, scan, edoc)';
COMMENT ON COLUMN IMAGE_FILE.FILE_ID				IS    'ECM 파일 아이디';
COMMENT ON COLUMN IMAGE_FILE.FILE_NAME				IS    '파일명';
COMMENT ON COLUMN IMAGE_FILE.FILE_ORDER 			IS '문서 정렬 순서';
COMMENT ON COLUMN IMAGE_FILE.CREATE_TIME 			IS    '생성시각';
COMMENT ON COLUMN IMAGE_FILE.MODIFY_TIME 			IS    '수정시각';


--index
CREATE  INDEX IX_IMAGE_STORE_01 		ON IMAGE_STORE(MAIN_KEY ASC, CREATE_TIME ASC) TABLESPACE TS_PPL_IMG_IDX_01;
CREATE  INDEX IX_IMAGE_FILE_01 			ON IMAGE_FILE(MAIN_KEY, CREATE_TIME ASC) TABLESPACE TS_PPL_IMG_IDX_01;

--sequence
CREATE SEQUENCE SQ_IMAGE_FILE_01 		START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CACHE 20 CYCLE ORDER;



-------------------------------------------------------------------
--주의! 사용자 정보 확인 (ppl_image_adm & ppl_ccrs_app 확인)
-------------------------------------------------------------------  
--grant (table)
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON ppl_img_dbadm.IMAGE_STORE		 	TO ppl_tran;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON ppl_img_dbadm.IMAGE_FILE		 		TO ppl_tran;

--grant (sequence)  
GRANT SELECT, ALTER ON ppl_img_dbadm.SQ_IMAGE_FILE_01 								TO ppl_tran;

------------------------------------------------------------------------------------------------------------------------------------------------
-- run in app 
------------------------------------------------------------------------------------------------------------------------------------------------
drop synonym IMAGE_STORE;
drop synonym IMAGE_FILE;

drop synonym SQ_IMAGE_FILE_01;

--Synonym (table)
CREATE SYNONYM IMAGE_STORE		 			FOR ppl_img_dbadm.IMAGE_STORE;	
CREATE SYNONYM IMAGE_FILE		 			FOR ppl_img_dbadm.IMAGE_FILE;

--Synonym (sequence)
CREATE SYNONYM SQ_IMAGE_FILE_01				FOR ppl_img_dbadm.SQ_IMAGE_FILE_01;

------------------------------------------------------------------------------------------------------------------------------------------------
--test

-- 시퀀스 순서 확인
SELECT SQ_IMAGE_FILE_01.NEXTVAL FROM DUAL;

COMMIT;


Insert into IMAGE_STORE (MAIN_KEY, BRANCH_CODE, GUIDE_NAME, EMPLOYEE_NAME, CUSTOMER_NAME, DOC_MAPPING_COUNT, PREVIOUS_DEVICE_INFO, INSOURCE_ID, MEMO, CREATE_TIME, MODIFY_TIME) values ('190621000001', 'branch-001', '안내자', '심사역', '채무자', 2, '192.168.0.101', 'CCRSTEST', 'mxg7Clm4ZHaHwGv6/ftWAw==', SYSDATE, NULL);
Insert into IMAGE_FILE (MAIN_KEY, DOC_ID, PAGE_CNT, DOC_TYPE, DELETE_YN, FUNNELS, FILE_ID, FILE_NAME, CREATE_TIME, MODIFY_TIME ) values ('190621000001','DOC-001',5,'PNG','N','SCAN','111111111111111', 'test.pdf', SYSDATE, sysdate);
Insert into IMAGE_FILE (MAIN_KEY, DOC_ID, PAGE_CNT, DOC_TYPE, DELETE_YN, FUNNELS, FILE_ID, FILE_NAME, CREATE_TIME, MODIFY_TIME ) values ('190621000001','DOC-002',3,'PDF','N','EDOC','111111111111111', 'test.pdf', SYSDATE, sysdate);